### ISSUE TITLE
Pull requests from non-collaborator forked repositories failed due missing env var

### ISSUE THREAD

**Issue by jjperezaguinaga** [oceanprotocol/pleuston#159]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
> Running latest version of develop tagged on `e7a4b6a`
- [X] I checked the documentation and found no answer
> No clear location for documentation other than the README 😢 , opening that as a new issue.
- [X] I checked to make sure that this issue has not already been filed
> ✅ 
- [X] I'm reporting the issue to the correct repository.
> Indeed, this is related to `pleuston` repository missing an environment variable.

## Expected Behavior

>Please describe the behavior you are expecting.
A pull-request should be able to grab a `Token` environment variable from Travis.

## Current Behavior

>What is the current behavior? Please provide as many details as possible.
See #158. Builds fail as it's missing the variable, as can be seen [here](https://travis-ci.com/oceanprotocol/pleuston/jobs/156160539).

## Step to Reproduce the problem

>Please provide detailed steps for reproducing the issue.

1. Create a pull request as non-collaborator from a forked repository
2. Watch the build complain about the missing token 

### Possible Solution

Issue seems to appear in non-collaborator pull requests, so there are a couple ways to solve it:

- Create a set of specific jobs in Travis that can pass secrets and use a development account so no production secrets are passed.
- Copy this pull request's branch and push it to upstream with one of your collaborators.
- Provide some information in how to include this information locally or through Travis.

## Specifications

>Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

No required for this issue.

## Failure Logs

>Please include any relevant log snippets or files here.
```
[error] "2018-11-03T18:43:59.471Z"  'Error sending coverage'
[error] "2018-11-03T18:43:59.473Z"  Error: Token is required
    at Object.module.exports [as handleInput] (/home/travis/build/oceanprotocol/pleuston/node_modules/codacy-coverage/lib/handleInput.js:22:35)
    at Socket.<anonymous> (/home/travis/build/oceanprotocol/pleuston/node_modules/codacy-coverage/bin/codacy-coverage.js:48:20)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @oceanprotocol/pleuston@0.1.0 test: `npm run lint && node scripts/test.js --env=jsdom --coverage && cat ./coverage/lcov.info | codacy-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @oceanprotocol/pleuston@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-03T18_43_59_489Z-debug.log
The command "npm run test" exited with 1.
27.83s$ npm run build
```
More can be seen in the following failed Travis build - https://travis-ci.com/oceanprotocol/pleuston/jobs/156160539

**Comment by jjperezaguinaga** [comment]
Upon inspecting the code it seems that the issue is in the following line
```
    "test": "npm run lint && node scripts/test.js --env=jsdom --coverage && cat ./coverage/lcov.info | codacy-coverage"
```
In short, you are expecting a token for `codacy-coverage`, but that token is not available to your forked repositories.

Here's a very good [breakdown](https://blog.algolia.com/travis-encrypted-variables-external-contributions/) on why this is the case. You could either pass those secrets to your forks, or use a key provider service like [algolia created](https://github.com/algolia/api-key-dealer). We can poke at various options.
