### ISSUE TITLE
`npm run build` fails

### ISSUE THREAD

**Issue by jcortejoso** [oceanprotocol/pleuston#97]
Hi!

I am facing an error when trying to start pleuston (in branches develop and master):

```+ npm run build

> @oceanprotocol/pleuston@0.1.0 build /pleuston
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

./src/index.js


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @oceanprotocol/pleuston@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @oceanprotocol/pleuston@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-10T21_13_50_585Z-debug.log
+ serve -l tcp://0.0.0.0:3000 -s /pleuston/build/
ERROR: Cannot copy to clipboard: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

+ cat /root/.npm/_logs/2018-09-10T21_13_50_585Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @oceanprotocol/pleuston@0.1.0~prebuild: @oceanprotocol/pleuston@0.1.0
6 info lifecycle @oceanprotocol/pleuston@0.1.0~build: @oceanprotocol/pleuston@0.1.0
7 verbose lifecycle @oceanprotocol/pleuston@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @oceanprotocol/pleuston@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/pleuston/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @oceanprotocol/pleuston@0.1.0~build: CWD: /pleuston
10 silly lifecycle @oceanprotocol/pleuston@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle @oceanprotocol/pleuston@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle @oceanprotocol/pleuston@0.1.0~build: Failed to exec build script
13 verbose stack Error: @oceanprotocol/pleuston@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @oceanprotocol/pleuston@0.1.0
15 verbose cwd /pleuston
16 verbose Linux 4.9.93-linuxkit-aufs
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @oceanprotocol/pleuston@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the @oceanprotocol/pleuston@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

+ node scripts/build.js

Creating an optimized production build...
Failed to compile.

./src/index.js
```

Thanks!

**Comment by kremalicious** [comment]
weird, can't reproduce locally on macOS with both, Node.js 8 & 9. Seems something is missing in Docker container

**Comment by kremalicious** [comment]
At least this message: `ERROR: Cannot copy to clipboard: Couldn't find the required `xsel` binary.` shouldn't be a problem, it's just `serve` failing to copy the url to clipboard

**Comment by jcortejoso** [comment]
I think the problem is related with the file `.eslintrc`, that was being ignored inside the Docker container.

**Comment by kremalicious** [comment]
AMAZING, who would have thought. Definitely `.eslintrc` is needed during build process because of this step https://github.com/oceanprotocol/pleuston/blob/develop/config/webpack.config.prod.js#L177
